- name: Copy hosts file
  hosts: all,!nginx
  tasks:
  - name: Create directories
    shell: mkdir -p /home/vagrant/hosts
  - name: Copy id
    copy:
      src: /home/vagrant/.ssh/id_rsa
      dest: /home/vagrant/.ssh/id_rsa
  - name: Copy files 
    copy:
      src: /home/vagrant/hosts/hosts
      dest: /home/vagrant/hosts/hosts
  - name: Exec shell hosts
    shell: cat /home/vagrant/hosts/hosts >> /etc/hosts
  - name: Exec shell hosts template    
    shell: cat /home/vagrant/hosts/hosts >> /etc/cloud/templates/hosts.debian.tmpl
  - name: Test  proxy
    shell: apt install traceroute
