  - hosts: gitlab
    become: true
    roles:
      - ansible-role-gitlab
        #- ansible-letsencrypt-nginx-revproxy
    vars:
      gitlab_domain: gitlab.petrivanov.ru
      gitlab_external_url: "https://gitlab.petrivanov.ru/"
