  - hosts: nginx
    roles:
      - ansible-nginx-revproxy
        #- ansible-letsencrypt-nginx-revproxy
    vars:
      nginx_revproxy_sites:
        petrivanov.ru:
          domains:
            - www.petrivanov.ru
            - test.petrivanov.ru
            - gitlab.petrivanov.ru
            - grafana.petrivanov.ru
            - prometheus.petrivanov.ru
            - alertmanager.petrivanov.ru
          upstreams:
            - { backend_address: 192.168.10.30, backend_port: 80 }
            - { backend_address: 192.168.10.10, backend_port: 80 }
            - { backend_address: 192.168.10.40, backend_port: 80 }
            - { backend_address: 192.168.10.50, backend_port: 80 }
            - { backend_address: 192.168.10.50, backend_port: 80 }
            - { backend_address: 192.168.10.50, backend_port: 80 }
          letsencrypt: true
          ssl: true
          letsencrypt_email: black.skif@gmail.com
          letsencrypt_stage: false
